/* fadelabel.c generated by valac 0.12.0, the Vala compiler
 * generated from fadelabel.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gdk/gdk.h>
#include <stdio.h>


#define TYPE_FADE_LABEL (fade_label_get_type ())
#define FADE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FADE_LABEL, FadeLabel))
#define FADE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FADE_LABEL, FadeLabelClass))
#define IS_FADE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FADE_LABEL))
#define IS_FADE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FADE_LABEL))
#define FADE_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FADE_LABEL, FadeLabelClass))

typedef struct _FadeLabel FadeLabel;
typedef struct _FadeLabelClass FadeLabelClass;
typedef struct _FadeLabelPrivate FadeLabelPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _FadeLabel {
	GtkLabel parent_instance;
	FadeLabelPrivate * priv;
	gchar* active_colour;
	gchar* inactive_colour;
};

struct _FadeLabelClass {
	GtkLabelClass parent_class;
};

struct _FadeLabelPrivate {
	gint active_duration;
	gint fade_duration;
	gdouble fade_level;
	guint idle;
};


static gpointer fade_label_parent_class = NULL;

GType fade_label_get_type (void) G_GNUC_CONST;
#define FADE_LABEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_FADE_LABEL, FadeLabelPrivate))
enum  {
	FADE_LABEL_DUMMY_PROPERTY
};
FadeLabel* fade_label_new (const gchar* message, const gchar* active_colour, const gchar* inactive_colour);
FadeLabel* fade_label_construct (GType object_type, const gchar* message, const gchar* active_colour, const gchar* inactive_colour);
void fade_label_set_text (FadeLabel* self, const gchar* message, gint duration);
gboolean fade_label_fade_start (FadeLabel* self);
static gboolean _fade_label_fade_start_gsource_func (gpointer self);
gboolean fade_label_fade_out (FadeLabel* self);
static gboolean _fade_label_fade_out_gsource_func (gpointer self);
static void fade_label_finalize (GObject* obj);


FadeLabel* fade_label_construct (GType object_type, const gchar* message, const gchar* active_colour, const gchar* inactive_colour) {
	FadeLabel * self = NULL;
	g_return_val_if_fail (message != NULL, NULL);
	g_return_val_if_fail (active_colour != NULL, NULL);
	g_return_val_if_fail (inactive_colour != NULL, NULL);
	self = (FadeLabel*) g_object_new (object_type, NULL);
	fade_label_set_text (self, message, 0);
	if (g_strcmp0 (active_colour, "") == 0) {
		active_colour = "#ffffff";
	} else {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (active_colour);
		_g_free0 (self->active_colour);
		self->active_colour = _tmp0_;
	}
	if (g_strcmp0 (inactive_colour, "") == 0) {
		inactive_colour = "#000000";
	} else {
		gchar* _tmp1_;
		_tmp1_ = g_strdup (inactive_colour);
		_g_free0 (self->inactive_colour);
		self->inactive_colour = _tmp1_;
	}
	return self;
}


FadeLabel* fade_label_new (const gchar* message, const gchar* active_colour, const gchar* inactive_colour) {
	return fade_label_construct (TYPE_FADE_LABEL, message, active_colour, inactive_colour);
}


static gboolean _fade_label_fade_start_gsource_func (gpointer self) {
	gboolean result;
	result = fade_label_fade_start (self);
	return result;
}


void fade_label_set_text (FadeLabel* self, const gchar* message, gint duration) {
	GdkColor colour = {0};
	GdkColor _tmp0_ = {0};
	FadeLabel* _tmp1_;
	guint _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (message != NULL);
	if (duration == 0) {
		duration = self->priv->active_duration;
	}
	gdk_color_parse (self->active_colour, &_tmp0_);
	colour = _tmp0_;
	gtk_widget_modify_fg ((GtkWidget*) self, GTK_STATE_NORMAL, &colour);
	_tmp1_ = self;
	gtk_label_set_text (GTK_IS_LABEL (_tmp1_) ? ((GtkLabel*) _tmp1_) : NULL, message);
	if (self->priv->idle != 0) {
		g_source_remove (self->priv->idle);
	}
	_tmp2_ = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) duration, _fade_label_fade_start_gsource_func, g_object_ref (self), g_object_unref);
	self->priv->idle = _tmp2_;
}


static gboolean _fade_label_fade_out_gsource_func (gpointer self) {
	gboolean result;
	result = fade_label_fade_out (self);
	return result;
}


gboolean fade_label_fade_start (FadeLabel* self) {
	gboolean result = FALSE;
	guint _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	fprintf (stderr, "starting a fade");
	self->priv->fade_level = (gdouble) 1;
	if (self->priv->idle != 0) {
		g_source_remove (self->priv->idle);
	}
	_tmp0_ = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 25, _fade_label_fade_out_gsource_func, g_object_ref (self), g_object_unref);
	self->priv->idle = _tmp0_;
	result = TRUE;
	return result;
}


gboolean fade_label_fade_out (FadeLabel* self) {
	gboolean result = FALSE;
	GdkColor colour = {0};
	GdkColor _tmp0_ = {0};
	guint16 red1;
	guint16 green1;
	guint16 blue1;
	GdkColor _tmp1_ = {0};
	guint16 red2;
	guint16 green2;
	guint16 blue2;
	g_return_val_if_fail (self != NULL, FALSE);
	gdk_color_parse (self->inactive_colour, &_tmp0_);
	colour = _tmp0_;
	red1 = colour.red;
	green1 = colour.green;
	blue1 = colour.blue;
	gdk_color_parse (self->active_colour, &_tmp1_);
	colour = _tmp1_;
	red2 = colour.red;
	green2 = colour.green;
	blue2 = colour.blue;
	colour.red = red1 + ((guint16) (self->priv->fade_level * (red2 - red1)));
	colour.green = green1 + ((guint16) (self->priv->fade_level * (green2 - green1)));
	colour.blue = blue1 + ((guint16) (self->priv->fade_level * (blue2 - blue1)));
	gtk_widget_modify_fg ((GtkWidget*) self, GTK_STATE_NORMAL, &colour);
	self->priv->fade_level = self->priv->fade_level - (1.0 / (self->priv->fade_duration / 25));
	if (self->priv->fade_level > 0) {
		result = TRUE;
		return result;
	}
	self->priv->idle = (guint) 0;
	result = FALSE;
	return result;
}


static void fade_label_class_init (FadeLabelClass * klass) {
	fade_label_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (FadeLabelPrivate));
	G_OBJECT_CLASS (klass)->finalize = fade_label_finalize;
}


static void fade_label_instance_init (FadeLabel * self) {
	gchar* _tmp0_;
	gchar* _tmp1_;
	self->priv = FADE_LABEL_GET_PRIVATE (self);
	self->priv->active_duration = 3000;
	self->priv->fade_duration = 1500;
	self->priv->fade_level = (gdouble) 0;
	self->priv->idle = (guint) 0;
	_tmp0_ = g_strdup ("#ffffff");
	self->active_colour = _tmp0_;
	_tmp1_ = g_strdup ("#000000");
	self->inactive_colour = _tmp1_;
}


static void fade_label_finalize (GObject* obj) {
	FadeLabel * self;
	self = FADE_LABEL (obj);
	_g_free0 (self->active_colour);
	_g_free0 (self->inactive_colour);
	G_OBJECT_CLASS (fade_label_parent_class)->finalize (obj);
}


GType fade_label_get_type (void) {
	static volatile gsize fade_label_type_id__volatile = 0;
	if (g_once_init_enter (&fade_label_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FadeLabelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) fade_label_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FadeLabel), 0, (GInstanceInitFunc) fade_label_instance_init, NULL };
		GType fade_label_type_id;
		fade_label_type_id = g_type_register_static (GTK_TYPE_LABEL, "FadeLabel", &g_define_type_info, 0);
		g_once_init_leave (&fade_label_type_id__volatile, fade_label_type_id);
	}
	return fade_label_type_id__volatile;
}



